pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
//     environment {
//         DEBUG = 'true'
//     }
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select Action')
    }
    stages {
        stage('Init') {
            steps { 
                  withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                       sh """
                            cd 00-vpc 
                            terraform init -reconfigure
                            terraform plan -out=tfplan
                       """
                  }
            }                       
        }         
    }
    post { 
        always { 
            echo 'This session runs always'
            deleteDir()
        }
        success { 
            echo 'This session runs when pipeline success'
        }
        failure { 
            echo 'This session runs when pipeline failure'
        }
    }
}

